create table if not exists public.renovation_pages (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  content_json jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

insert into public.renovation_pages (slug, content_json)
values ('main', '{}'::jsonb)
on conflict (slug) do nothing;

alter table public.renovation_pages enable row level security;

create policy "anonymous can read renovation page"
on public.renovation_pages
for select
to anon
using (true);
